### ISSUE TITLE
Support a generic module folder for cache

### ISSUE THREAD

**Issue by rtritto** [radarsu/ts-import#23]
From README:
```console
Caches JavaScript files into directory inside node_modules/ts-import/cache (pretty much like typescript-require). Removing node_modules removes cache as well.
```

Not all package managers use `node_modules` as target folder to save modules.
An example is _yarn Berry_, with Plug'n'Play enabled (pnp loader), that use `./yarn/cache` or global cache folder instead of `node_modules` one.

### Reproduction
- `yarn init -y`
- `yarn set version canary`
- `yarn add typescript ts-import`
- Create `a.js` file:
```js
const { loadSync } = require('ts-import')

loadSync('./b.ts')
```
- Create `b.ts` file:
```ts
// empty (not relevant)
```
- `yarn node a.js`

### Actual
```console
C:\test-ts-import\.pnp.cjs:162
  return Object.assign(new Error(`${code}: ${message}`), { code });
                       ^

Error: EROFS: read-only filesystem, mkdir '/node_modules/ts-import/cache'
    at makeError$1 (C:\test-ts-import\.pnp.cjs:162:24)
    at EROFS (C:\test-ts-import\.pnp.cjs:189:10)
    at ZipFS.mkdirSync (C:\test-ts-import\.pnp.cjs:8553:13)
    at ZipFS.mkdirpSync (C:\test-ts-import\.pnp.cjs:1007:16)
    at ZipFS.mkdirSync (C:\test-ts-import\.pnp.cjs:8551:19)
    at C:\test-ts-import\.pnp.cjs:2408:22
    at C:\test-ts-import\.pnp.cjs:2584:66
    at ZipOpenFS.getMountSync (C:\test-ts-import\.pnp.cjs:2694:14)
    at ZipOpenFS.makeCallSync (C:\test-ts-import\.pnp.cjs:2584:17)
    at ZipOpenFS.mkdirSync (C:\test-ts-import\.pnp.cjs:2405:17) {
  code: 'EROFS'
}
```

### Expected
No error log

### Possible fix
Replace cache folder from `/node_modules/ts-import/cache` to `/.ts-import/cache`.

---

I did a try with:
```js
loadSync('./b.ts', {
  transpileOptions: {
    cache: {
      dir: '.ts-import/cache'
    }
  }
})
```
but I got:
```console
C:\test-ts-import\.pnp.cjs:9029
      Error.captureStackTrace(firstError);
            ^

Error: ts-import tried to access .ts-import, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: .ts-import (via ".ts-import\cache\test-ts-import\b.js")
Required by: ts-import@virtual:9e7a180dc0f89c8a8d9bf223af9ddaa14921360be209e54695bf056928c5818bfd4c7e66276fa9292d9daa944d3ec353f952ab3011e7cf01001bd27be602ba25#npm:4.0.0-beta.8 (via C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\)

Require stack:
- C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\main.js
- C:\test-ts-import\a.js
    at Function.require$$0.Module._resolveFilename (C:\test-ts-import\.pnp.cjs:9029:13)
    at Function.require$$0.Module._load (C:\test-ts-import\.pnp.cjs:8880:42)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadSync (C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\main.js:76:20)
    at Object.<anonymous> (C:\test-ts-import\a.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require$$0.Module._extensions..js (C:\test-ts-import\.pnp.cjs:9073:33)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
```
Fixed adding a link with `yarn add .ts-import@link:./.ts-import`

**Comment by radarsu** [comment]
I've replaced cache folder /node_modules/ts-import/cache with /.cache/ts-import by default. I prefer top-level type-grouped directories instead of library-grouped (/.config/library-name over /.library-name/config). It usually leads to less clutter in main directory (there are a lot of libraries there, but there is quite limited scope of types of directories they may want to use).

The tradeoff is that some library may already be generating .cache directory in a way that isn't compatible with sharing that directory with different vendors, but I'll take that.

This is released in `4.0.0-beta.10` version.
