### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by rtritto** [radarsu/ts-import#24]
### Reproduction with nodeLinker: pnp
- `yarn init -y`
- `yarn set version canary`
- `yarn add typescript ts-import`
- Add in `package.json`:
```json
  "type": "module"
```
- Create `a.js` file:
```js
import { loadSync } from 'ts-import'

loadSync('./b.ts', {
  transpileOptions: {
    cache: {
      dir: '.ts-import/cache'
    }
  }
})
```
- Create `b.ts` file:
```ts
// empty (not relevant)
```
- `yarn node a.js`

### Actual
<details><summary>Output</summary>

```console
C:\test-ts-import\.pnp.cjs:9081
        Error.captureStackTrace(err);
              ^

Error: require() of ES Module C:\test-ts-import\.ts-import\cache\test-ts-import\b.js from C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\main.js not supported.
Instead change the require of b.js in C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\main.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require$$0.Module._extensions..js (C:\test-ts-import\.pnp.cjs:9081:15)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.require$$0.Module._load (C:\test-ts-import\.pnp.cjs:8923:14)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadSync (C:\test-ts-import\.yarn\__virtual__\ts-import-virtual-d1ab32303e\3\Users\<User>\AppData\Local\Yarn\Berry\cache\ts-import-npm-4.0.0-beta.8-9c304f6bdb-9.zip\node_modules\ts-import\dist\main.js:76:20)
    at file:///C:/test-ts-import/a.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24) {
  code: 'ERR_REQUIRE_ESM'
}
```
</details>

### Expected
No error log

---

### Reproduction with nodeLinker: node-modules
- `yarn init -y`
- `yarn set version canary`
- `yarn add typescript ts-import`
- Add in `package.json`:
```json
  "type": "module"
```
- Create `a.js` file:
```js
import { loadSync } from 'ts-import'

loadSync('./b.ts', {
  transpileOptions: {
    cache: {
      dir: '.ts-import/cache'
    }
  }
})
```
- Create `b.ts` file:
```ts
// empty (not relevant)
```
- Add to `.yarnrc.yml` file
```yml
nodeLinker: node-modules
```
- `yarn node a.js`

### Actual
<details><summary>Output</summary>

```console
C:\test-ts-import\node_modules\ts-import\dist\main.js:72
            const loaded = require(jsPath);
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\test-ts-import\.ts-import\cache\test-ts-import\b.js from C:\test-ts-import\node_modules\ts-import\dist\main.js not supported.
b.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename b.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\test-ts-import\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at loadSync (C:\test-ts-import\node_modules\ts-import\dist\main.js:72:28)
    at file:///C:/test-ts-import/a.js:4:1
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

</details>

### Expected
No error log

---

I did a try with:
```js
import ts from 'typescript'
import { loadSync } from 'ts-import'

loadSync('./b.ts', {
  transpileOptions: {
    cache: {
      dir: '.ts-import/cache'
    },
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      moduleResolution: ts.ModuleResolutionKind.Node16
    }
  }
})
```
and I got same error.

---

### How to fix
https://github.com/radarsu/ts-import/blob/2561e9418774f8aaf4414c6772720950441bffd6/src/main.ts#L75
Check if it's ESM (`type: module`) and use `.cjs` extension, otherwise use `.js`.

### Workaround
- `yarn patch ts-import`
- Go to created folder and edit _/dist/main.js_ with:
```diff
@@ -57,7 +57,7 @@ const loadSync = (tsRelativePath, options) => {
     const cacheDir = providers.getCacheDir(config);
     const tsPath = path.resolve(cwd, tsRelativePath);
     const jsAfterCachePath = crossPlatform.getJsAfterCachePath(tsPath);
-    const jsPath = path.join(cacheDir, jsAfterCachePath).replace(/\.[^/.]+$/u, `.js`);
+    const jsPath = path.join(cacheDir, jsAfterCachePath).replace(/\.[^/.]+$/u, `.cjs`);
     if (loadConfig.useCache) {
         const tsFileExists = utils.checkIfFileExistsSync(tsPath);
         let jsFileExists;
```
- `yarn patch-commit -s "<created_folder_path>"`
- `yarn`

Note:
If you need for _ts-import_ load method:
```diff
@@ -27,7 +27,7 @@ const load = async (tsRelativePath, options) => {
     const cacheDir = providers.getCacheDir(config);
     const tsPath = path.resolve(cwd, tsRelativePath);
     const jsAfterCachePath = crossPlatform.getJsAfterCachePath(tsPath);
-    const jsPath = path.join(cacheDir, jsAfterCachePath).replace(/\.[^/.]+$/u, `.js`);
+    const jsPath = path.join(cacheDir, jsAfterCachePath).replace(/\.[^/.]+$/u, `.cjs`);
     if (loadConfig.useCache) {
         const [tsFileExists, jsFileExists] = await Promise.all([
             utils.checkIfFileExists(tsPath),
```

**Comment by radarsu** [comment]
I've released `4.0.0-beta.10` version, in which I went one step further and instead of boolean `esm` flag I've added `compiledJsExtension` parameter that simply can be set to `.cjs` or whatever. I've added tests to cover that is working, but haven't tested yet in a project with package.json using `"type": "module"`.

Please let me know if it's working well for your use-case.
